[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plusins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'markonm/traces.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo ='Shougo/ddc.vim'

#[[plugins]]
#repo = 'Shougo/pum.vim'

#[[plugins]]
#repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'Shougo/ddc-ui-native'

[[plugins]]
repo = 'Shougo/ddc-source-around'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

#[[plugins]]
#repo = 'Shougo/ddc-sorter_rank'

#[[plugins]]
#repo = 'Shougo/ddc-converter_remove_overlap'

[[plugins]]
repo = 'shun/ddc-source-vim-lsp'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'biosugar0/vim-popyank'

[[plugins]]
repo = 'skanehira/denops-translate.vim'

#[[plugins]]
#repo = 'fatih/vim-go'

[[plugins]]
repo = 'Yggdroot/indentLine'
