[general]
import = [
  "~/.config/alacritty/theme.toml"
]

[window]
padding = {x=4,y=2}
opacity = 0.75
blur = true

[scrolling]
history = 100000
multiplier = 5

[font]
size = 14.0
# offset = {x=0,y=4}
normal = { family = "HackGen Console NF", style="Regular" }
bold = { family = "HackGen Console NF", style="Bold" }
italic = { family = "HackGen Console NF", style="Italic" }
bold_italic = { family = "HackGen Console NF", style="Bold Italic" }
