#background_opacity: 0.7

scrolling:
  history: 10000
  multiplier: 3


raw_bold_text_with_bright_colors: true

# Cyberpunk-Neon colours
colors:
  # Default colours
  primary:
    background: '0x000b1e'
    foreground: '0x0abdc6'

  # Colors that should be used to draw the terminal cursor. If these are unset,
  # the cursor colour will be the inverse of the cell colour.
  # cursor:
  #   text: '0x2e2e2d'
  #   # text: '0x000000'
  #   cursor: '0xffffff'

  # Normal colors
  normal:
    black:   '0x123e7c'
    red:     '0xff0000'
    green:   '0xd300c4'
    yellow:  '0xf57800'
    blue:    '0x123e7c'
    magenta: '0x711c91'
    cyan:    '0x0abdc6'
    white:   '0xd7d7d5'

  # Bright colors
  bright:
    black:   '0x1c61c2'
    red:     '0xff0000'
    green:   '0xd300c4'
    yellow:  '0xf57800'
    blue:    '0x00ff00'
    magenta: '0x711c91'
    cyan:    '0x0abdc6'
    white:   '0xd7d7d5'

  # dim colors
  dim:
    black:   '0x1c61c2'
    red:     '0xff0000'
    green:   '0xd300c4'
    yellow:  '0xf57800'
    blue:    '0x123e7c'
    magenta: '0x711c91'
    cyan:    '0x0abdc6'
    white:   '0xd7d7d5'


# Font
font:
  size: 14
  normal:
    family: 'UDEV Gothic NFLG'
    style: Regular
  bold:
    family: 'UDEV Gothic NFLG'
    style: Bold
      #  italic:
      #    family: 'RictyDiminished NF'
      #    style: Italic
      #  bold_italic:
      #    family: 'RictyDiminished NF'
      #    style: Bold Itali

# env
env:
  TERM: alacritty
