# ZDOTDIR
export ZDOTDIR=${HOME}/.config/zsh

# XDG
export XDG_CONFIG_HOME=${HOME}/.config
export XDG_CACHE_HOME=${HOME}/.cache
export XDG_DATA_HOME=${HOME}/.local/share
export XDG_STATE_HOME=${HOME}/.local/state

# path
export PATH=${HOME}/.local/bin:$PATH
export PATH=${HOME}/.cargo/bin:$PATH

# editor
export EDITOR=nvim
export CVSEDITOR="${EDITOR}"
export SVN_EDITOR="${EDITOR}"
export GIT_EDITOR="${EDITOR}"

# history
## 履歴ファイルの保存先
export HISTFILE=${HOME}/.config/zsh/.zsh_history
export HISTSIZE=1000
export SAVEHIST=100000
export HISTFILESIZE=100000
## 記録
setopt hist_ignore_dups
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt hist_save_no_dups
setopt hist_no_store
setopt hist_verify
setopt hist_reduce_blanks
setopt hist_expand
## 開始・終了を記録
setopt EXTENDED_HISTORY
## history共有
setopt share_history

# other
export LISTMAX=50
unsetopt bg_nice
setopt list_packed
setopt no_beep
unsetopt list_types
setopt print_eight_bit
setopt correct

## rust
#source "${HOME}/.cargo/env"

#python
#alias python="python3"

# added by Nix installer
if [ -e ${HOME}/.nix-profile/etc/profile.d/nix.sh ]; then . ${HOME}/.nix-profile/etc/profile.d/nix.sh; fi 
